services:
  mariadb:
    image: mariadb:11.4
    container_name: college-library-mariadb
    environment:
      MARIADB_DATABASE: library_management
      MARIADB_USER: library_user
      MARIADB_PASSWORD: library_password
      MARIADB_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  postgres:
    image: postgres:16
    container_name: college-library-postgres
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mariadb_data:
  postgres_data:
