spring:
  application:
    name: library-management
  datasource:
    url: jdbc:h2:mem:library_management;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  profiles:
    default: local

server:
  port: 8080

app:
  security:
    allowed-origins: http://localhost:5173
