spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/library_management}
    username: ${DB_USERNAME:library_user}
    password: ${DB_PASSWORD:library_password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

app:
  security:
    allowed-origins: "${ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://192.168.*.*:5173,http://10.*.*.*:5173,http://172.*.*.*:5173,https://localhost:5173,https://127.0.0.1:5173,https://192.168.*.*:5173,https://10.*.*.*:5173,https://172.*.*.*:5173,http://localhost:5174,http://127.0.0.1:5174,http://192.168.*.*:5174,http://10.*.*.*:5174,http://172.*.*.*:5174,https://localhost:5174,https://127.0.0.1:5174,https://192.168.*.*:5174,https://10.*.*.*:5174,https://172.*.*.*:5174}"
